version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menuqr-app
    restart: unless-stopped
    working_dir: /var/www/core
    environment:
      - APP_NAME=MenuQR
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=panel.chatxbots.com
      - DB_PORT=8080
      - DB_DATABASE=difyserver
      - DB_USERNAME=mysql
      - DB_PASSWORD=5be557415b86d4fc437a
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - PHP_MEMORY_LIMIT=1024M
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=100M
    volumes:
      - .:/var/www
    networks:
      - menuqr-network

  webserver:
    image: nginx:alpine
    container_name: menuqr-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - menuqr-network

networks:
  menuqr-network:
    driver: bridge