version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menuqr-app
    restart: unless-stopped
    working_dir: /var/www/core
    environment:
      - DB_HOST=difyserver_menuqrdb
      - DB_PORT=3306
      - DB_DATABASE=difyserver
      - DB_USERNAME=mysql
      - DB_PASSWORD=5be557415b86d4fc437a
    volumes:
      - .:/var/www
      - ./logs/php:/var/log/php
      - ./logs/laravel:/var/www/core/storage/logs
    networks:
      - menuqr-network
      - difyserver_default

  webserver:
    image: nginx:alpine
    container_name: menuqr-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - menuqr-network

networks:
  menuqr-network:
    driver: bridge
  difyserver_default:
    external: true