version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menuqr-app
    restart: unless-stopped
    working_dir: /var/www/core
    environment:
      - APP_NAME=MenuQR
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=menuqr
      - DB_USERNAME=menuqr_user
      - DB_PASSWORD=menuqr123
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - PHP_MEMORY_LIMIT=1024M
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=100M
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - menuqr-network

  webserver:
    image: nginx:alpine
    container_name: menuqr-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - menuqr-network

  db:
    image: mysql:5.7
    container_name: menuqr-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: menuqr
      MYSQL_ROOT_PASSWORD: menuqr123
      MYSQL_PASSWORD: menuqr123
      MYSQL_USER: menuqr_user
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - menuqr-network

networks:
  menuqr-network:
    driver: bridge

volumes:
  dbdata: